<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Vehicle Info</name>
   <tag></tag>
   <elementGuidId>3ee3f64d-af1c-4d4e-8e25-6bf145514b50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tblVehicleBody']/tr/td[8]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.d-none.d-sm-inline-block.btn.btn-sm.btn-info.shadow-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>36ce9f08-7386-4e25-b76a-fcb6828e5e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>VehicleInfo.jsp?aid=3885</value>
      <webElementGuid>cd285a08-b4f0-4ffa-b530-66ff693047fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-sm-inline-block btn btn-sm btn-info shadow-sm</value>
      <webElementGuid>8ab8e981-219a-4200-88b3-ffeccad9f842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> View Vehicle Info</value>
      <webElementGuid>c9dbd66a-bb9a-44ac-88cf-c75a8627cbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblVehicleBody&quot;)/tr[1]/td[8]/a[@class=&quot;d-none d-sm-inline-block btn btn-sm btn-info shadow-sm&quot;]</value>
      <webElementGuid>e145fd5e-cee0-43e4-b38c-ce5d083d1f79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblVehicleBody']/tr/td[8]/a</value>
      <webElementGuid>09c1c084-5d9d-471e-aab6-3aa9d95bce75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Vehicle Info')]</value>
      <webElementGuid>fd899513-d3ba-48f6-a7b6-ed8da61d4733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KPYS2004201'])[1]/following::a[1]</value>
      <webElementGuid>e55d14cc-84b3-46b0-a833-140cf0aaeb2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KPYS2E004257'])[1]/following::a[1]</value>
      <webElementGuid>db42edf0-ff7d-46e6-a8d6-9544779a2803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO Institution'])[2]/preceding::a[1]</value>
      <webElementGuid>752543b5-584a-4037-b7e9-62316f235ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Branch'])[2]/preceding::a[1]</value>
      <webElementGuid>deffa069-dafa-4d2c-8654-14cf7871ec15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Vehicle Info']/parent::*</value>
      <webElementGuid>d6ea4fd1-5b04-4d38-a818-936aab96b77d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'VehicleInfo.jsp?aid=3885')]</value>
      <webElementGuid>bd242943-6dcd-440d-973c-24f5cd88af82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a</value>
      <webElementGuid>96218905-ae7c-4133-b88a-24d34fa9bf3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'VehicleInfo.jsp?aid=3885' and (text() = ' View Vehicle Info' or . = ' View Vehicle Info')]</value>
      <webElementGuid>18af4621-0262-4d6f-8688-fc09d8e1e207</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
