<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Delivered</name>
   <tag></tag>
   <elementGuidId>6502ea2b-80e7-4cce-a0d9-e0f79bc1fee5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapseCar']/div/a[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c4690b84-c214-487e-ab4d-c3e9678e98f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collapse-item</value>
      <webElementGuid>213884b4-0724-4cb3-bd77-190a3ef374e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Vehicle.jsp?vh=102&amp;vht=104&amp;page=1</value>
      <webElementGuid>343472c4-33d4-4a42-9b87-8223244477e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delivered</value>
      <webElementGuid>a74ea638-0d0b-4ff4-87b9-a9c8f44c9635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseCar&quot;)/div[@class=&quot;bg-white py-2 collapse-inner rounded&quot;]/a[@class=&quot;collapse-item&quot;]</value>
      <webElementGuid>0cf0e8e6-dcf8-47dc-bfa1-7448e7a49a65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseCar']/div/a[4]</value>
      <webElementGuid>ea693feb-aa47-4cee-aa74-f3fdc57d2d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Delivered')])[2]</value>
      <webElementGuid>9ead03de-93e1-4723-853e-9ed6af11948b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved'])[2]/following::a[2]</value>
      <webElementGuid>3b54bbe9-0385-4255-ba1c-5508e0287e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disposed'])[2]/preceding::a[1]</value>
      <webElementGuid>2c4a7a47-0ef1-480e-9eb5-aeae17ec4b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other Assets'])[1]/preceding::a[2]</value>
      <webElementGuid>f123c803-68f9-4bfc-99ac-5238fcd71bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Vehicle.jsp?vh=102&amp;vht=104&amp;page=1')]</value>
      <webElementGuid>887769f5-1a5f-46da-9cc3-4da590864740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/div/a[4]</value>
      <webElementGuid>09409893-4652-4d28-85cf-c5ef504609de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Vehicle.jsp?vh=102&amp;vht=104&amp;page=1' and (text() = 'Delivered' or . = 'Delivered')]</value>
      <webElementGuid>97c7735e-284e-4805-9a0d-70b38330acc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
