<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Open Info</name>
   <tag></tag>
   <elementGuidId>cd3a26da-a32e-4d00-b67a-2f239c2b2ecb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tblVehicleBody']/tr/td[8]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(8) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0d68b010-7097-4eb5-bf7e-03e7ba1b1fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>0858078f-6d4c-4d0c-94c8-a6641aeafb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open Info</value>
      <webElementGuid>0801b9a4-a663-4313-b3c9-e51330268661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblVehicleBody&quot;)/tr[1]/td[8]/a[1]</value>
      <webElementGuid>a65782f5-9414-4bd0-81c2-729577987bc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblVehicleBody']/tr/td[8]/a</value>
      <webElementGuid>66cd65fd-c7b8-4d72-bfd1-9e9ae1310d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Open Info')]</value>
      <webElementGuid>239b6921-b30c-46b6-87ae-fcc519099717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAEL65MYFFB015481'])[1]/following::a[1]</value>
      <webElementGuid>b302960e-1a39-45e4-b640-c2083579e27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Polar White'])[1]/following::a[1]</value>
      <webElementGuid>12e41593-66be-4f17-b2ef-9c39518da697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARD INC'])[1]/preceding::a[1]</value>
      <webElementGuid>81e2ca35-89a6-42d4-921e-08df379e526e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MINDANAO 3'])[1]/preceding::a[1]</value>
      <webElementGuid>d6ec66dc-ecfd-46b9-b3a3-1ccbc202bd8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Open Info']/parent::*</value>
      <webElementGuid>29968e77-9143-4044-a16e-024e6ec5f6fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[12]</value>
      <webElementGuid>29e3cb7b-6e64-4f45-93cd-dba12817b5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a</value>
      <webElementGuid>33552c9f-cae5-4890-a87d-a9fe2dfcb520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Open Info' or . = 'Open Info')]</value>
      <webElementGuid>66035709-41ac-4501-8c14-7979d3884e22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
