<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Print MOR Document</name>
   <tag></tag>
   <elementGuidId>f6e7ccb4-a3da-4f35-ad4a-8e4f3c0d46f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mordiv']/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bafe82fe-11e9-433e-8bf2-6a2d7df147f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>c352130c-c526-431f-82d2-fb421c8d9450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>morreport.jsp?mor=--&amp;brand=Honda&amp;branditem=XRM125&amp;engine=KPYS2E004257&amp;chasis=KPYS2004201&amp;color=Red&amp;dtaq=2019-02-08</value>
      <webElementGuid>cf2f1570-978c-4083-a8fd-e6a6c68459c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>c59610c6-db81-4c72-a292-8332ed2de636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Print MOR Document</value>
      <webElementGuid>b75092be-b277-4ddb-b6d9-5a9ec389e158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mordiv&quot;)/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>419e638b-5968-4ffd-ac7d-233f1870fc6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mordiv']/a[2]</value>
      <webElementGuid>b5ecd4c8-e907-436d-9429-c7aa8ecf1bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Print MOR Document')]</value>
      <webElementGuid>8ebea08c-2406-49c7-aac9-73c9ff6d3bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options:'])[2]/following::a[2]</value>
      <webElementGuid>3b96384d-3701-47ea-9789-0bb7e5eac494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Institution :'])[1]/preceding::a[1]</value>
      <webElementGuid>a9a44cdf-5f8a-4d2f-a13b-62912ed11a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO Institution'])[1]/preceding::a[1]</value>
      <webElementGuid>3a010588-069c-4950-9805-63e229e2b8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Print MOR Document']/parent::*</value>
      <webElementGuid>42784c50-7431-4521-a599-041697ad00da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'morreport.jsp?mor=--&amp;brand=Honda&amp;branditem=XRM125&amp;engine=KPYS2E004257&amp;chasis=KPYS2004201&amp;color=Red&amp;dtaq=2019-02-08')]</value>
      <webElementGuid>a8c61d9f-9184-441f-a52a-30c78dde9d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a[2]</value>
      <webElementGuid>60361d9e-9dde-404a-83f4-bbce6d79f49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'morreport.jsp?mor=--&amp;brand=Honda&amp;branditem=XRM125&amp;engine=KPYS2E004257&amp;chasis=KPYS2004201&amp;color=Red&amp;dtaq=2019-02-08' and (text() = 'Print MOR Document' or . = 'Print MOR Document')]</value>
      <webElementGuid>af45a5f7-ec9a-4254-9279-645f362144ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
