<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Update VehicleResponsibility</name>
   <tag></tag>
   <elementGuidId>cebccf28-f0cb-4df5-80fc-32e65828e8c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='setupdateResponsibility()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mordiv > a.dropdown-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7c94c9fb-d34b-4d99-88c0-345c55e91c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>0cac61e8-43fb-4d74-9490-35868c033efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>0cc72eb8-58d7-46f2-8ca9-6663dd476d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setupdateResponsibility()</value>
      <webElementGuid>b2c0b2df-b0e9-4b4f-bf93-e887133fe43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update Vehicle
												Responsibility</value>
      <webElementGuid>87d061fe-31ab-4013-8c83-6802345a5113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mordiv&quot;)/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>357eec89-f6d8-4553-a4da-025f9a3b3adb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='setupdateResponsibility()']</value>
      <webElementGuid>869695f6-3c9e-49d6-a8ef-53eb93f0cee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mordiv']/a</value>
      <webElementGuid>51cc74c4-3c91-42e5-811e-150edd661bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Update Vehicle
												Responsibility')]</value>
      <webElementGuid>2f4f92c3-9e1f-44a3-9990-4a62bc3e5279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options:'])[2]/following::a[1]</value>
      <webElementGuid>fa223c86-e5b4-47e1-9dde-1877b04ae2b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print MOR Document'])[1]/preceding::a[1]</value>
      <webElementGuid>82805a57-992e-443f-a95e-c082e7142b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Institution :'])[1]/preceding::a[2]</value>
      <webElementGuid>5d1f583c-489a-4056-ba12-fa4517142b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[15]</value>
      <webElementGuid>4564d30d-0c34-46a7-ba7a-a16e7b3ece29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/a</value>
      <webElementGuid>6435d185-30da-4ca7-83cc-ca794a8c9fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Update Vehicle
												Responsibility' or . = 'Update Vehicle
												Responsibility')]</value>
      <webElementGuid>66c33194-1e4f-4ea0-84aa-ddcbcc98218c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
