<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Billing Code  Reference OR Remarks Da_1095d3</name>
   <tag></tag>
   <elementGuidId>c78323df-c435-4236-886f-51e7f9c87be1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vhb_txtBCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vhb_txtBCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ec348ad-f4f5-4151-9b6b-071e35572a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61fc9338-5546-4c26-b2ed-9763c4f689a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vhb_txtBCode</value>
      <webElementGuid>ee402ed5-6594-46a1-b41e-35fdcdc42014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vhb_txtBCode</value>
      <webElementGuid>0e201ce9-0854-4ebf-8606-26066b8ff818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vhb_txtBCode&quot;)</value>
      <webElementGuid>f6e6d96a-0295-4b76-b731-1364211abb9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vhb_txtBCode']</value>
      <webElementGuid>730259ee-67f2-4bfe-bcb1-bb0217d96197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EditBillingPayment']/div/div/div[2]/input</value>
      <webElementGuid>9994b6cf-2552-42fa-9a59-92a947338bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/input</value>
      <webElementGuid>f4d152e2-8884-429a-9482-b26020fa3b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vhb_txtBCode' and @id = 'vhb_txtBCode']</value>
      <webElementGuid>174767bf-a250-43b3-8acf-6084803b6e25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
